name: gensimtest
dependencies:
- cython=0.23.4=py34_0
- gensim=0.10.3=np19py34_0
- libgfortran=1.0=0
- numpy=1.9.3=py34_0
- openblas=0.2.14=3
- openssl=1.0.1k=1
- pip=7.1.2=py34_0
- python=3.4.3=1
- readline=6.2=2
- scipy=0.16.0=np19py34_1
- setuptools=18.4=py34_0
- six=1.10.0=py34_0
- sqlite=3.8.4.1=1
- system=5.8=2
- tk=8.5.18=0
- wheel=0.26.0=py34_1
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - boto==2.38.0
  - bz2file==0.98
  - httpretty==0.8.6
  - nltk==3.1
  - requests==2.8.0
  - smart-open==1.3.
